# 1단계: Build Stage
FROM node:20 AS builder
WORKDIR /app
# 의존성 설치
COPY package*.json ./
RUN npm install
# 소스 복사 및 빌드
COPY . .
RUN npm run build

# 2단계: Run Stage
FROM node:20-alpine
WORKDIR /app
# 빌드 결과물만 복사
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
# 운영용 의존성만 설치
RUN npm install --production

CMD ["npm", "start"]

EXPOSE 3000